#!/usr/bin/env python3
"""Diagnose: Are escape codes in PTY output or terminal responses?

This script runs the terminal tool directly and captures its raw output
WITHOUT displaying it to the terminal. This lets us see if escape codes
are being captured as part of the command output vs generated by terminal
responses.
"""

import re
import sys

from openhands.tools.terminal.definition import TerminalAction
from openhands.tools.terminal.terminal.factory import create_terminal_session


print("=" * 60)
print("DIAGNOSTIC: Source of Escape Codes")
print("=" * 60)
print(f"stdin.isatty(): {sys.stdin.isatty()}")
print(f"stdout.isatty(): {sys.stdout.isatty()}")
print()


print("Creating terminal session...")
session = create_terminal_session(
    work_dir="/tmp",
    username=None,
    no_change_timeout_seconds=30,
)
session.initialize()

print("Running: gh pr list --repo OpenHands/openhands --limit 3")
print()

# Execute command and capture output
action = TerminalAction(
    command="gh pr list --repo OpenHands/openhands --limit 3",
    is_input=False,
    timeout=30,
)
result = session.execute(action)

print("=" * 60)
print("RAW CAPTURED OUTPUT (repr):")
print("=" * 60)
# Show the raw output with escape codes visible
raw_output = result.text if hasattr(result, "text") else str(result)
print(repr(raw_output))

print()
print("=" * 60)
print("ESCAPE SEQUENCE ANALYSIS:")
print("=" * 60)

# Check for common escape sequences
escape_patterns = [
    (b"\x1b[", "CSI (Control Sequence Introducer)"),
    (b"\x1b]", "OSC (Operating System Command)"),
    (b"\x1bP", "DCS (Device Control String)"),
    (b"\x1b\\", "ST (String Terminator)"),
]

raw_bytes = raw_output.encode("utf-8", errors="replace")
found_any = False

for pattern, name in escape_patterns:
    count = raw_bytes.count(pattern)
    if count > 0:
        found_any = True
        print(f"  Found {count}x {name} sequences")

        # Find and show the sequences
        if pattern == b"\x1b[":
            # CSI sequences end with a letter
            matches = re.findall(rb"\x1b\[[0-9;]*[A-Za-z]", raw_bytes)
            for m in matches[:5]:  # Show up to 5
                print(f"    - {m!r}")
        elif pattern == b"\x1b]":
            # OSC sequences end with BEL or ST
            matches = re.findall(rb"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)", raw_bytes)
            for m in matches[:5]:
                print(f"    - {m!r}")

if not found_any:
    print("  No escape sequences found in captured output!")

print()
print("=" * 60)
print("CONCLUSION:")
print("=" * 60)

if found_any:
    print("  Escape codes ARE in the PTY captured output.")
    print("  The gh command is writing these to its stdout.")
    print("  FIX: Filter escape sequences from terminal tool output.")
else:
    print("  Escape codes are NOT in captured output.")
    print("  They must be coming from terminal responses to Rich queries.")
    print("  FIX: Echo suppression should work (check implementation).")

print()
session.close()
print("Session closed.")
